line-length = 120
exclude = [
	"cgit/osmo-commit-filter.py",
	"net/fill_config.py",
	"net/templates/freeswitch/python/dialplan-dgsm/__init__.py",
	"osmo-cn-latest/provision-hlr.py",
	"sysmobts-calib.py",
]
include = [
	"*.py",
	"src/grd",
]

[lint]
ignore = [
	"B026",    # https://docs.astral.sh/ruff/rules/star-arg-unpacking-after-keyword-arg/
	"E741",    # https://docs.astral.sh/ruff/rules/ambiguous-variable-name/
	"EXE001",  # https://docs.astral.sh/ruff/rules/shebang-not-executable/
	"I001",    # https://docs.astral.sh/ruff/rules/unsorted-imports/
	"PLR1730", # https://docs.astral.sh/ruff/rules/if-stmt-min-max/
	"SIM103",  # https://docs.astral.sh/ruff/rules/needless-bool/
	"SIM115",  # https://docs.astral.sh/ruff/rules/open-file-with-context-handler/
	"UP031",   # https://docs.astral.sh/ruff/rules/printf-string-formatting/
]

[format]
exclude = [
	"cgit/osmo-commit-filter.py",
	"gen_makefile.py",
	"net/fill_config.py",
	"net/templates/freeswitch/python/dialplan-dgsm/__init__.py",
	"osmo-cn-latest/provision-hlr.py",
	"sysmobts-calib.py",
]
