line-length = 120
exclude = [
	"cgit/osmo-commit-filter.py",
	"net/fill_config.py",
	"net/templates/freeswitch/python/dialplan-dgsm/__init__.py",
	"osmo-cn-latest/provision-hlr.py",
	"sysmobts-calib.py",
]

[lint]
# E741: Ambiguous variable name: `l`
ignore = ["E741"]
